#%RAML 1.0
    title: A RESTful API for a user & device management server

/api/v1:
  /accounts/:
    description: User accounts on the server
    post:
      description: Creates a user account on the server
      body:
        application/json:
          type: user
          example: |
            {
              "email": "sick@account.com",
              "password": "password",
              "first_name": "George",
              "last_name": "Anderson"
            }
      responses:
        201:
          body:
            application/json:
              example: |
                {
                  "id": "b3dcb087-6b9e-470e-977d-38f03dad5cf4",
                  "email": "sick@account.com",
                  "first_name": "George",
                  "last_name": "Anderson",
                  "access_token": "laksjdhfljahsdbvfklabsdfkjh2384ysdjfhba770aw3br087bawfs",
                  "password": "pbkdf2_sha256$36000$2IuAdqcZlhDq$O9G/EykpJiu4X0ddhkrUARpbQ6gqeYi+cfe0g34Gf5I="
                }
    /session/:
      post:
        description: Creates a new login session for a user
        headers:
          authorization:
            description: HTTP Basic Auth header
            required: true
            type: string
            example: Basic YUBhLmNvbTpxdw== 
        response:
          example: |
            {
              "user": {
                  "email": "a@a.com",
                  "first_name": "FirstName",
                  "last_name": "LastName"
              },
              "token": "0bebe5f987d33d8d02e8c2791a3b9ab5a4488606057049bb3cc8d8eb931de4be",
              "access_token" : "lkajshdfjasiikhdfjahsd1298hw8dgf0af098qh23rh7asd0fga0s87dfasef"
            }
  /devices/:
    post:
      description: Creates a device on the server 
      headers:
        Authorization:
          description: A valid authorization token for the owning user
          required: true
          type: string
          example: Token asldkjfljh23lkjfsldkjfhasSeCReTToKEN
        Cookie:
          description: cookie containing CSRF token issued by django
          required: true
          type: string
          example: csrftoken=asldkjfljh23lkjfsldkjfhasSeCReTToKEN
        body:
          application/json:
            type: device 
            example: |
              {
                "deviceId": "somenumbersasdf123",
                "type": 1,
              }
    get:
      description: Get a list of devices for a user
      headers:
        Authorization:
          description: A valid authorization token for the owning user
          required: true
          type: string
          example: Token asldkjfljh23lkjfsldkjfhasSeCReTToKEN
      response:
        example: |
        {
            "count": 3,
            "next": null,
            "previous": null,
            "results": [
                {
                    "id": 2,
                    "deviceId": "myotherdevice",
                    "deviceType": 1,
                    "deviceName": null,
                    "group": 21
                },
                {
                    "id": 1,
                    "deviceId": "mydevice",
                    "deviceType": 1,
                    "deviceName": null,
                    "group": 21
                },
                {
                    "id": 3,
                    "deviceId": "myotherdevice1",
                    "deviceType": 1,
                    "deviceName": "dfdfdfy",
                    "group": null
                }
            ]
        }
    /{deviceID}/:
      get:
        description: Get a device
        headers:
          Authorization:
            description: A valid authorization token for the owning user
            required: true
            type: string
            example: Token asldkjfljh23lkjfsldkjfhasSeCReTToKEN
      put:
        description: Update device details
        headers:
          Authorization:
            description: A valid authorization token for the owning user
            required: true
            type: string
            example: Token asldkjfljh23lkjfsldkjfhasSeCReTToKEN
          Cookie:
            description: cookie containing CSRF token issued by django
            required: true
            type: string
            example: csrftoken=asldkjfljh23lkjfsldkjfhasSeCReTToKEN
        body:
          application/json:
            type: device 
      /sensordata/:
        /all/:
          get:
            description: Get all data for this device
            headers:
              Authorization:
                description: A valid authorization token for the owning user
                required: true
                type: string
                example: Token asldkjfljh23lkjfsldkjfhasSeCReTToKEN
            queryParameters:
              count:
                displayName: count
                type: integer
                description: Number of temp readings to get.
                example: 2
                required: false
        /temp/:
          get:
            description: Get temperature data for this device
            headers:
              Authorization:
                description: A valid authorization token for the owning user
                required: true
                type: string
                example: Token asldkjfljh23lkjfsldkjfhasSeCReTToKEN
            queryParameters:
              count:
                displayName: count
                type: integer
                description: Number of temp readings to get.
                example: 2
                required: false
    /groups/:
      /types/:
        post:
          description: Creates a new group type. Defines global group states
          headers:
            Authorization:
               description: A valid authorization token for the owning user
               required: true
               type: string
               example: Token asldkjfljh23lkjfsldkjfhasSeCReTToKEN
            Cookie:
              description: cookie containing CSRF token issued by django
              required: true
              type: string
              example: csrftoken=asldkjfljh23lkjfsldkjfhasSeCReTToKEN
          body:
            application/json:
              example: | 
                {
                  "name":"Burglar Alarm",
                  "states" : [
                    "ARMED",
                    "DISARMED"
                  ]
                }
      post:
        description: Creates a new group of devices
        headers:
          Authorization:
             description: A valid authorization token for the owning user
             required: true
             type: string
             example: Token asldkjfljh23lkjfsldkjfhasSeCReTToKEN
          Cookie:
            description: cookie containing CSRF token issued by django
            required: true
            type: string
            example: csrftoken=asldkjfljh23lkjfsldkjfhasSeCReTToKEN
        body:
          application/json:
            example: | 
              {
                "name":"my first burglar alarm",
                "type" : 1,
                "devices" : [
                  "my-device-ID",
                  "my-other-device-ID"
                ]
              }
        responses:
          201:
            body:
              application/json:
                example: |
                  {
                    "id": 21,
                    "name": "burglar alarm"
                  }
      get:
        description: Get a list of groups a user has
        headers:
          Authorization:
             description: A valid authorization token for the owning user
             required: true
             type: string
             example: Token asldkjfljh23lkjfsldkjfhasSeCReTToKEN
          Cookie:
            description: cookie containing CSRF token issued by django
            required: true
            type: string
            example: csrftoken=asldkjfljh23lkjfsldkjfhasSeCReTToKEN
        responses:
          200:
            body:
              application/json:
                example: | 
      /{groupID}/:
        get:
          description: Get a specific group
            Authorization:
                description: A valid authorization token for the owning user
                required: true
                type: string
                example: Token asldkjfljh23lkjfsldkjfhasSeCReTToKEN
            Cookie:
                description: cookie containing CSRF token issued by django
                required: true
                type: string
                example: csrftoken=asldkjfljh23lkjfsldkjfhasSeCReTToKEN
        /triggers/: 
          post:
            description: Create a trigger for a group of devices

