version: '2'

services:
    nginx:
        extends:
            file: docker-common.yml
            service: nginx
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - backend
        expose:
            - 80
    postgres:
        extends:
            file: docker-common.yml
            service: postgres
        ports:
            - 5433:5432
        volumes:
            - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    backend:
        extends:
            file: docker-common.yml
            service: django
        links:
            - postgres

        env_file: .env
        entrypoint:
            - /django-entrypoint.sh
    frontend:
        extends:
            file: docker-common.yml
            service: web
        links:
            - backend
        entrypoint:
            - /web-entrypoint.sh
