# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_devicename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceId',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
