# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20180201_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='value',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
