# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20180211_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroupTypeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, unique=True)),
                ('devicegrouptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='devices.DeviceGroupType')),
            ],
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='groupType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceGroupType'),
            preserve_default=False,
        ),
    ]
