# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20180211_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroupTypeVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=50)),
                ('devicegrouptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='devices.DeviceGroupType')),
            ],
        ),
        migrations.AlterField(
            model_name='devicegrouptypestate',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
