# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20180212_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegroup',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceGroupTypeState'),
            preserve_default=False,
        ),
    ]
