# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_devicegroup_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetype',
            old_name='value',
            new_name='name',
        ),
        migrations.AddField(
            model_name='devicegrouptypevariable',
            name='variableType',
            field=models.CharField(default='integer', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicetype',
            name='description',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='firmwareVersion',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='devicetypefunc',
            name='funcName',
            field=models.CharField(max_length=50),
        ),
    ]
