# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20180213_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroupTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceGroup')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroupTriggerLocalAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcName', models.CharField(max_length=50)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localActions', to='devices.DeviceGroupTrigger')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroupTriggerOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='devicegrouptrigger',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceGroupTriggerOperator'),
        ),
        migrations.AddField(
            model_name='devicegrouptrigger',
            name='valuetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceGroupTypeVariable'),
        ),
    ]
