# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20180214_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicegrouptriggerlocalaction',
            name='funcName',
        ),
        migrations.AddField(
            model_name='devicegrouptriggerlocalaction',
            name='function',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceTypeFunc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicegrouptriggerlocalaction',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceGroupTrigger'),
        ),
        migrations.RemoveField(
            model_name='devicetypefunc',
            name='devicetype',
        ),
        migrations.AddField(
            model_name='devicetypefunc',
            name='devicetype',
            field=models.ManyToManyField(to='devices.DeviceType'),
        ),
    ]
