# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_auto_20180214_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.DeviceGroup'),
        ),
        migrations.AlterField(
            model_name='devicegrouptriggerlocalaction',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localActions', to='devices.DeviceGroupTrigger'),
        ),
    ]
