# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_deviceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegrouptrigger',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceGroupTypeState'),
            preserve_default=False,
        ),
    ]
