# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_auto_20180226_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceGroup')),
            ],
        ),
        migrations.RenameModel(
            old_name='DeviceGroupTriggerLocalAction',
            new_name='TriggerLocalAction',
        ),
        migrations.RenameModel(
            old_name='DeviceGroupTriggerOperator',
            new_name='TriggerOperator',
        ),
        migrations.RemoveField(
            model_name='devicegrouptrigger',
            name='group',
        ),
        migrations.RemoveField(
            model_name='devicegrouptrigger',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='devicegrouptrigger',
            name='state',
        ),
        migrations.RemoveField(
            model_name='devicegrouptrigger',
            name='valuetype',
        ),
        migrations.AddField(
            model_name='devicetypefunc',
            name='param',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Trigger'),
        ),
        migrations.AlterField(
            model_name='triggerlocalaction',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localActions', to='devices.Trigger'),
        ),
        migrations.DeleteModel(
            name='DeviceGroupTrigger',
        ),
        migrations.AddField(
            model_name='trigger',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.TriggerOperator'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceGroupTypeState'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='valuetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceGroupTypeVariable'),
        ),
    ]
