# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_auto_20180306_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerlocalaction',
            name='param',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
