# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_userlocation'),
        ('devices', '0018_triggerlocalaction_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zones.Zone'),
        ),
    ]
